export const LOGINSUCCESS="LOGINSUCCESS"
export const LOGINGFAILURE="LOGINGFAILURE"
export const SIGNUPSUCCESS="SIGNUPSUCCESS"
export const SIGNUPFAILURE="SIGNUPFAILURE"

export const TASKADDEDSUCCESS="TASKADDEDSUCCESS"
export const TASKADDEDFAILURE="TASKADDEDFAILURE"
export const TASKEDITEDSUCCESS="TASKEDITEDSUCCESS"
export const TASKEDITEDFAILURE="TASKEDITEDFAILURE"
export const TASKDELETEDSUCCESS="TASKDELETEDSUCCESS"
export const TASKDELETEDFAILURE="TASKDELETEDFAILURE"
export const TASKDETAILSSUCCESS="TASKDETAILSSUCCESS"
export const TASKDETAILSFAILURE="TASKDETAILSFAILURE"

export const TASKSTATUSSUCCESS="TASKSTATUSSUCCESS"
export const TASKSTATUSFAILURE="TASKSTATUSFAILURE"




export const USERDETAILSSUCCESS="USERDETAILSSUCCESS"
export const USERDETAILSFAILURE="USERDETAILSFAILURE"







